### ISSUE TITLE
SIG submenu out of date

### ISSUE THREAD

**Issue by MichaelChan-Pong** [UniversityOfFloridaACM/WebAPP#27]
The SIG submenu is missing certain new SIGs including:

* Financial Technology Group
* Open Source Club
* Digital Arts and Science Club

**Comment by progdude** [comment]
@MichaelChan-Pong We've just added the new SIGS to the submenu and they are currently going through the PR process. They should be ready soon. Sorry for the wait!

**Comment by nicolasiscoding** [comment]
@progdude @MichaelChan-Pong Reviewing PR Now

**Comment by andrewjkerr** [comment]
@progdude generally it's not a good idea to close out tickets before the corresponding PR is merged. :)
