### ISSUE TITLE
Show "No events coming up!" message when there are no events to display in the event stream

### ISSUE THREAD

**Issue by MichaelChan-Pong** [UniversityOfFloridaACM/WebAPP#29]
Probably wouldn't be used too much, but for times such as breaks when there aren't any events coming up, it'd be nice to see something other than an empty event stream.

**Comment by progdude** [comment]
Good Point! We'll see what we can do!

**Comment by andrewjkerr** [comment]
I've opened a PR for this (#30). Please give it a try. :)
