### ISSUE TITLE
Can we do end to end testing so we can create a release 

### ISSUE THREAD

**Issue by nicolasiscoding** [UniversityOfFloridaACM/WebAPP#37]
I will then deploy

**Comment by MichaelChan-Pong** [comment]
define end-to-end testing.

**Comment by andrewjkerr** [comment]
Write automated tests to fully test the functionality of the site. For example, you'll write tests for signing up, logging in, uploading a resume, etc. It's a lofty goal....

**Comment by progdude** [comment]
@MichaelChan-Pong mentioned this to me a few days ago. I have a list of items that need to be tested. I'll talk to Michael so we can get the unit tests started.

**Comment by MichaelChan-Pong** [comment]
yea, I could take this up, but I have no idea how long it'll take for me to do it. I'm still figuring out how to do unit testing, and it'll take some time to figure out how to use Selenium to test buttons and stuff.

**Comment by nicolasiscoding** [comment]
Use mocha and chai. But for now for the sake of a new deploy, just test it manually please

**Comment by nicolasiscoding** [comment]
Selenium for front end too

**Comment by MichaelChan-Pong** [comment]
I'm planning on using mocha, chai, selenium, and more to write the unit tests. I'm still figuring out how do to things like test whether the login works and all.
