### ISSUE TITLE
Create "Our Sponsors" Page

### ISSUE THREAD

**Issue by nicolasiscoding** [UniversityOfFloridaACM/WebAPP#6]
Our sponsors for this academic year are:

State Farm Bronze
AirWatch Silver
Bloomberg Gold
Infinite Energy Gold

Gold has the largest presence on the page, than Silver, than Bronze

**Comment by MichaelChan-Pong** [comment]
I can handle this if I can get more detail on what this page would comprise of. @nicolasiscoding

**Comment by andrewjkerr** [comment]
It wasn't a page, but the sponsors are listed on the index page (#25) so I'm going to close this one out. @nicolasiscoding feel free to re-open if you'd like to move them to a new page.
